export const ReleaseDownloads = ({ lang = "zh-CN" }) => {
  const RELEASES_PAGE = "https://github.com/dsh-tauri/deepseek-harness-desktop/releases"
  const PLATFORM_ORDER = ["windows", "macos", "linux", "other"]

  /* sync-releases:start (generated by scripts/sync-releases.mjs — do not edit by hand) */
  const SNAPSHOT = [
    {
      "tag": "v0.17.2",
      "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/tag/v0.17.2",
      "published": "2026-09-25T17:21:38Z",
      "prerelease": false,
      "assets": [
        {
          "name": "Deepseek.Harness.Desktop_0.17.2_aarch64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.2/Deepseek.Harness.Desktop_0.17.2_aarch64.dmg",
          "size": "10.8 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.17.2_amd64.AppImage",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.2/Deepseek.Harness.Desktop_0.17.2_amd64.AppImage",
          "size": "90.1 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.17.2_amd64.deb",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.2/Deepseek.Harness.Desktop_0.17.2_amd64.deb",
          "size": "14 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.17.2_x64-setup.exe",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.2/Deepseek.Harness.Desktop_0.17.2_x64-setup.exe",
          "size": "7.44 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.17.2_x64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.2/Deepseek.Harness.Desktop_0.17.2_x64.dmg",
          "size": "11.6 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.17.2_x64_en-US.msi",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.2/Deepseek.Harness.Desktop_0.17.2_x64_en-US.msi",
          "size": "11 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.17.2_x64_zh-CN.msi",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.2/Deepseek.Harness.Desktop_0.17.2_x64_zh-CN.msi",
          "size": "11 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_Bundle_0.17.2.deb",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.2/Deepseek.Harness.Desktop_Bundle_0.17.2.deb",
          "size": "116 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_Bundle_0.17.2.exe",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.2/Deepseek.Harness.Desktop_Bundle_0.17.2.exe",
          "size": "56.9 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_Bundle_0.17.2_aarch64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.2/Deepseek.Harness.Desktop_Bundle_0.17.2_aarch64.dmg",
          "size": "105 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_Bundle_0.17.2_x64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.2/Deepseek.Harness.Desktop_Bundle_0.17.2_x64.dmg",
          "size": "108 MB"
        }
      ]
    },
    {
      "tag": "v0.17.1",
      "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/tag/v0.17.1",
      "published": "2026-09-24T15:23:43Z",
      "prerelease": false,
      "assets": [
        {
          "name": "Deepseek.Harness.Desktop_0.17.1_aarch64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.1/Deepseek.Harness.Desktop_0.17.1_aarch64.dmg",
          "size": "10.8 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.17.1_amd64.AppImage",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.1/Deepseek.Harness.Desktop_0.17.1_amd64.AppImage",
          "size": "90.1 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.17.1_amd64.deb",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.1/Deepseek.Harness.Desktop_0.17.1_amd64.deb",
          "size": "14.1 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.17.1_x64-setup.exe",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.1/Deepseek.Harness.Desktop_0.17.1_x64-setup.exe",
          "size": "7.41 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.17.1_x64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.1/Deepseek.Harness.Desktop_0.17.1_x64.dmg",
          "size": "11.6 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.17.1_x64_en-US.msi",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.1/Deepseek.Harness.Desktop_0.17.1_x64_en-US.msi",
          "size": "11 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.17.1_x64_zh-CN.msi",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.1/Deepseek.Harness.Desktop_0.17.1_x64_zh-CN.msi",
          "size": "11 MB"
        }
      ]
    },
    {
      "tag": "v0.17.0",
      "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/tag/v0.17.0",
      "published": "2026-09-23T17:31:51Z",
      "prerelease": false,
      "assets": [
        {
          "name": "Deepseek.Harness.Desktop_0.17.0_aarch64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.0/Deepseek.Harness.Desktop_0.17.0_aarch64.dmg",
          "size": "10.7 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.17.0_amd64.AppImage",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.0/Deepseek.Harness.Desktop_0.17.0_amd64.AppImage",
          "size": "90.1 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.17.0_amd64.deb",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.0/Deepseek.Harness.Desktop_0.17.0_amd64.deb",
          "size": "14 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.17.0_x64-setup.exe",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.0/Deepseek.Harness.Desktop_0.17.0_x64-setup.exe",
          "size": "7.37 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.17.0_x64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.0/Deepseek.Harness.Desktop_0.17.0_x64.dmg",
          "size": "11.6 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.17.0_x64_en-US.msi",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.0/Deepseek.Harness.Desktop_0.17.0_x64_en-US.msi",
          "size": "10.9 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.17.0_x64_zh-CN.msi",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.17.0/Deepseek.Harness.Desktop_0.17.0_x64_zh-CN.msi",
          "size": "10.9 MB"
        }
      ]
    },
    {
      "tag": "v0.16.0",
      "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/tag/v0.16.0",
      "published": "2026-09-23T12:45:50Z",
      "prerelease": false,
      "assets": [
        {
          "name": "Deepseek.Harness.Desktop_0.16.0_aarch64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0/Deepseek.Harness.Desktop_0.16.0_aarch64.dmg",
          "size": "10.7 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0_amd64.AppImage",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0/Deepseek.Harness.Desktop_0.16.0_amd64.AppImage",
          "size": "90 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0_amd64.deb",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0/Deepseek.Harness.Desktop_0.16.0_amd64.deb",
          "size": "13.9 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0_x64-setup.exe",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0/Deepseek.Harness.Desktop_0.16.0_x64-setup.exe",
          "size": "7.33 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0_x64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0/Deepseek.Harness.Desktop_0.16.0_x64.dmg",
          "size": "11.5 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0_x64_en-US.msi",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0/Deepseek.Harness.Desktop_0.16.0_x64_en-US.msi",
          "size": "10.9 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0_x64_zh-CN.msi",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0/Deepseek.Harness.Desktop_0.16.0_x64_zh-CN.msi",
          "size": "10.9 MB"
        }
      ]
    },
    {
      "tag": "v0.16.0-beta.3",
      "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/tag/v0.16.0-beta.3",
      "published": "2026-09-23T07:02:26Z",
      "prerelease": true,
      "assets": [
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.3_aarch64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.3/Deepseek.Harness.Desktop_0.16.0-beta.3_aarch64.dmg",
          "size": "10.7 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.3_amd64.AppImage",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.3/Deepseek.Harness.Desktop_0.16.0-beta.3_amd64.AppImage",
          "size": "90 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.3_amd64.deb",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.3/Deepseek.Harness.Desktop_0.16.0-beta.3_amd64.deb",
          "size": "13.9 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.3_x64-setup.exe",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.3/Deepseek.Harness.Desktop_0.16.0-beta.3_x64-setup.exe",
          "size": "7.32 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.3_x64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.3/Deepseek.Harness.Desktop_0.16.0-beta.3_x64.dmg",
          "size": "11.5 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.3_x64_en-US.msi",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.3/Deepseek.Harness.Desktop_0.16.0-beta.3_x64_en-US.msi",
          "size": "10.9 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.3_x64_zh-CN.msi",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.3/Deepseek.Harness.Desktop_0.16.0-beta.3_x64_zh-CN.msi",
          "size": "10.9 MB"
        }
      ]
    },
    {
      "tag": "v0.16.0-beta.2",
      "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/tag/v0.16.0-beta.2",
      "published": "2026-09-22T14:05:24Z",
      "prerelease": true,
      "assets": [
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.2_aarch64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.2/Deepseek.Harness.Desktop_0.16.0-beta.2_aarch64.dmg",
          "size": "10.7 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.2_amd64.AppImage",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.2/Deepseek.Harness.Desktop_0.16.0-beta.2_amd64.AppImage",
          "size": "90 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.2_amd64.deb",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.2/Deepseek.Harness.Desktop_0.16.0-beta.2_amd64.deb",
          "size": "13.9 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.2_x64-setup.exe",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.2/Deepseek.Harness.Desktop_0.16.0-beta.2_x64-setup.exe",
          "size": "7.31 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.2_x64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.2/Deepseek.Harness.Desktop_0.16.0-beta.2_x64.dmg",
          "size": "11.5 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.2_x64_en-US.msi",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.2/Deepseek.Harness.Desktop_0.16.0-beta.2_x64_en-US.msi",
          "size": "10.9 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.2_x64_zh-CN.msi",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.2/Deepseek.Harness.Desktop_0.16.0-beta.2_x64_zh-CN.msi",
          "size": "10.9 MB"
        }
      ]
    },
    {
      "tag": "v0.15.9",
      "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/tag/v0.15.9",
      "published": "2026-09-22T16:47:03Z",
      "prerelease": false,
      "assets": [
        {
          "name": "Deepseek.Harness.Desktop_0.15.9_aarch64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.15.9/Deepseek.Harness.Desktop_0.15.9_aarch64.dmg",
          "size": "10.7 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.15.9_amd64.AppImage",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.15.9/Deepseek.Harness.Desktop_0.15.9_amd64.AppImage",
          "size": "90 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.15.9_amd64.deb",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.15.9/Deepseek.Harness.Desktop_0.15.9_amd64.deb",
          "size": "13.9 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.15.9_x64-setup.exe",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.15.9/Deepseek.Harness.Desktop_0.15.9_x64-setup.exe",
          "size": "7.31 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.15.9_x64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.15.9/Deepseek.Harness.Desktop_0.15.9_x64.dmg",
          "size": "11.5 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.15.9_x64_en-US.msi",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.15.9/Deepseek.Harness.Desktop_0.15.9_x64_en-US.msi",
          "size": "10.9 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.15.9_x64_zh-CN.msi",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.15.9/Deepseek.Harness.Desktop_0.15.9_x64_zh-CN.msi",
          "size": "10.9 MB"
        }
      ]
    },
    {
      "tag": "v0.16.0-beta.1",
      "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/tag/v0.16.0-beta.1",
      "published": "2026-09-21T16:59:26Z",
      "prerelease": true,
      "assets": [
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.1_aarch64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.1/Deepseek.Harness.Desktop_0.16.0-beta.1_aarch64.dmg",
          "size": "10.7 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.1_amd64.AppImage",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.1/Deepseek.Harness.Desktop_0.16.0-beta.1_amd64.AppImage",
          "size": "90 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.1_amd64.deb",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.1/Deepseek.Harness.Desktop_0.16.0-beta.1_amd64.deb",
          "size": "13.8 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.1_x64-setup.exe",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.1/Deepseek.Harness.Desktop_0.16.0-beta.1_x64-setup.exe",
          "size": "7.33 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.1_x64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.1/Deepseek.Harness.Desktop_0.16.0-beta.1_x64.dmg",
          "size": "11.5 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.1_x64_en-US.msi",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.1/Deepseek.Harness.Desktop_0.16.0-beta.1_x64_en-US.msi",
          "size": "10.9 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.16.0-beta.1_x64_zh-CN.msi",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.16.0-beta.1/Deepseek.Harness.Desktop_0.16.0-beta.1_x64_zh-CN.msi",
          "size": "10.9 MB"
        }
      ]
    },
    {
      "tag": "v0.15.8",
      "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/tag/v0.15.8",
      "published": "2026-09-20T14:30:28Z",
      "prerelease": false,
      "assets": [
        {
          "name": "Deepseek.Harness.Desktop_0.15.8_aarch64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.15.8/Deepseek.Harness.Desktop_0.15.8_aarch64.dmg",
          "size": "10.7 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.15.8_amd64.AppImage",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.15.8/Deepseek.Harness.Desktop_0.15.8_amd64.AppImage",
          "size": "90 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.15.8_amd64.deb",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.15.8/Deepseek.Harness.Desktop_0.15.8_amd64.deb",
          "size": "13.9 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.15.8_x64-setup.exe",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.15.8/Deepseek.Harness.Desktop_0.15.8_x64-setup.exe",
          "size": "7.33 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.15.8_x64.dmg",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.15.8/Deepseek.Harness.Desktop_0.15.8_x64.dmg",
          "size": "11.5 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.15.8_x64_en-US.msi",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.15.8/Deepseek.Harness.Desktop_0.15.8_x64_en-US.msi",
          "size": "10.9 MB"
        },
        {
          "name": "Deepseek.Harness.Desktop_0.15.8_x64_zh-CN.msi",
          "url": "https://github.com/dsh-tauri/deepseek-harness-desktop/releases/download/v0.15.8/Deepseek.Harness.Desktop_0.15.8_x64_zh-CN.msi",
          "size": "10.9 MB"
        }
      ]
    }
  ]

  /* sync-releases:end */

  const TEXT = {
    "zh-CN": {
      version: "版本",
      previewTag: "预览版",
      published: "发布于",
      noAssets: "该版本没有可下载的安装包。",
      releaseNotes: "查看该版本的发布说明",
      allReleases: "全部版本",
      platforms: { windows: "Windows", macos: "macOS", linux: "Linux", other: "其他文件" },
      kinds: {
        winSetup: "安装程序（.exe）",
        winMsiZh: "MSI（简体中文）",
        winMsiEn: "MSI（英文）",
        winMsi: "MSI 安装包",
        macArm: "Apple Silicon（.dmg）",
        macIntel: "Intel 芯片（.dmg）",
        macDmg: "macOS（.dmg）",
        linuxDeb: "Debian / Ubuntu（.deb）",
        linuxAppImage: "AppImage",
        other: "其他文件",
      },
    },
    en: {
      version: "Version",
      previewTag: "pre-release",
      published: "Published",
      noAssets: "This release has no downloadable installers.",
      releaseNotes: "Read the release notes",
      allReleases: "All releases",
      platforms: { windows: "Windows", macos: "macOS", linux: "Linux", other: "Other files" },
      kinds: {
        winSetup: "Installer (.exe)",
        winMsiZh: "MSI (Simplified Chinese)",
        winMsiEn: "MSI (English)",
        winMsi: "MSI package",
        macArm: "Apple Silicon (.dmg)",
        macIntel: "Intel (.dmg)",
        macDmg: "macOS (.dmg)",
        linuxDeb: "Debian / Ubuntu (.deb)",
        linuxAppImage: "AppImage",
        other: "Other file",
      },
    },
  }

  const copy = TEXT[lang] ?? TEXT["zh-CN"]

  const classifyAsset = (name) => {
    const lower = name.toLowerCase()
    if (lower.endsWith("-setup.exe"))
      return { platform: "windows", kind: "winSetup", rank: 0 }
    if (lower.endsWith("_zh-cn.msi"))
      return { platform: "windows", kind: "winMsiZh", rank: 1 }
    if (lower.endsWith("_en-us.msi"))
      return { platform: "windows", kind: "winMsiEn", rank: 2 }
    if (lower.endsWith(".msi"))
      return { platform: "windows", kind: "winMsi", rank: 3 }
    if (lower.endsWith("aarch64.dmg") || lower.endsWith("arm64.dmg"))
      return { platform: "macos", kind: "macArm", rank: 0 }
    if (lower.endsWith("x64.dmg") || lower.endsWith("x86_64.dmg"))
      return { platform: "macos", kind: "macIntel", rank: 1 }
    if (lower.endsWith(".dmg"))
      return { platform: "macos", kind: "macDmg", rank: 2 }
    if (lower.endsWith(".deb"))
      return { platform: "linux", kind: "linuxDeb", rank: 0 }
    if (lower.endsWith(".appimage"))
      return { platform: "linux", kind: "linuxAppImage", rank: 1 }
    return { platform: "other", kind: "other", rank: 9 }
  }

  const formatDate = (value) => {
    if (!value)
      return null
    try {
      return new Date(value).toLocaleDateString(lang === "zh-CN" ? "zh-CN" : "en-US", {
        year: "numeric",
        month: "short",
        day: "numeric",
      })
    }
    catch {
      return null
    }
  }

  const groupAssets = (assets) => {
    const buckets = { windows: [], macos: [], linux: [], other: [] }
    for (const asset of assets ?? []) {
      const meta = classifyAsset(asset.name ?? "")
      buckets[meta.platform].push({
        key: `${meta.platform}:${asset.name}`,
        label: copy.kinds[meta.kind],
        name: asset.name,
        url: asset.url,
        size: asset.size,
        rank: meta.rank,
      })
    }
    return PLATFORM_ORDER
      .filter(platform => buckets[platform].length > 0)
      .map(platform => ({
        platform,
        label: copy.platforms[platform],
        items: buckets[platform].sort((a, b) => a.rank - b.rank),
      }))
  }

  const releases = [...SNAPSHOT].sort((a, b) => (b.published ?? "").localeCompare(a.published ?? ""))
  const [selected, setSelected] = useState((releases.find(item => !item.prerelease) ?? releases[0])?.tag ?? null)
  const release = releases.find(item => item.tag === selected) ?? releases[0]

  if (release === undefined) {
    return (
      <div className="not-prose rounded-2xl border border-zinc-950/10 dark:border-white/10 px-4 py-5 text-sm text-zinc-950/60 dark:text-white/60">
        {copy.noAssets}
      </div>
    )
  }

  const groups = groupAssets(release.assets)
  const published = formatDate(release.published)

  return (
    <div className="not-prose">
      <div className="flex flex-wrap items-center gap-x-3 gap-y-2">
        <label className="text-sm text-zinc-950/70 dark:text-white/70" htmlFor={`dsh-release-${lang}`}>
          {copy.version}
        </label>
        <select
          id={`dsh-release-${lang}`}
          className="rounded-lg border border-zinc-950/15 dark:border-white/20 bg-transparent px-2.5 py-1.5 text-sm font-medium text-zinc-950 dark:text-white"
          value={release.tag}
          onChange={event => setSelected(event.target.value)}
        >
          {releases.map(item => (
            <option key={item.tag} value={item.tag}>
              {item.tag}
              {item.prerelease ? ` · ${copy.previewTag}` : ""}
            </option>
          ))}
        </select>
        {published
          ? <span className="text-sm text-zinc-950/60 dark:text-white/60">{`${copy.published} ${published}`}</span>
          : null}
        <a
          className="text-sm text-zinc-950/60 dark:text-white/60 underline decoration-zinc-950/20 dark:decoration-white/20 underline-offset-2"
          href={release.url}
          target="_blank"
          rel="noreferrer"
        >
          {copy.releaseNotes}
        </a>
        <a
          className="text-sm text-zinc-950/60 dark:text-white/60 underline decoration-zinc-950/20 dark:decoration-white/20 underline-offset-2"
          href={RELEASES_PAGE}
          target="_blank"
          rel="noreferrer"
        >
          {copy.allReleases}
        </a>
      </div>

      {groups.length === 0
        ? <p className="mt-4 text-sm text-zinc-950/60 dark:text-white/60">{copy.noAssets}</p>
        : groups.map(group => (
            <div key={group.platform} className="mt-6">
              <p className="text-sm font-medium text-zinc-950 dark:text-white">{group.label}</p>
              <div className="mt-2 flex flex-wrap gap-2">
                {group.items.map(item => (
                  <a
                    key={item.key}
                    className="inline-flex items-baseline gap-2 rounded-lg border border-zinc-950/15 dark:border-white/20 px-3 py-2 text-sm font-medium text-zinc-950 dark:text-white hover:border-zinc-950/30 dark:hover:border-white/40"
                    href={item.url}
                    title={item.name}
                  >
                    <span>{item.label}</span>
                    {item.size
                      ? <span className="text-xs font-normal text-zinc-950/50 dark:text-white/50">{item.size}</span>
                      : null}
                  </a>
                ))}
              </div>
            </div>
          ))}
    </div>
  )
}
